/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim
         * @description The first person in claims the instance and becomes its administrator. Refused once anybody exists.
         */
        post: operations["claim_api_auth_claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/instance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instance Status */
        get: operations["instance_status_api_auth_instance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_auth_me_patch"];
        trace?: never;
    };
    "/api/auth/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_auth_me_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Info */
        get: operations["session_info_api_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sudo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sudo
         * @description Re-authenticate for a few minutes before destructive actions.
         */
        post: operations["sudo_api_auth_sudo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bodymap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Body Map */
        get: operations["get_body_map_api_bodymap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image */
        get: operations["get_image_api_images__image_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Image
         * @description Moves the image to the trash; the purge and the garbage collection of blobs arrive with data management.
         */
        delete: operations["delete_image_api_images__image_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{image_id}/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Image File
         * @description The bytes, only for people who may see the person; cacheable forever because the content is addressed by hash.
         */
        get: operations["image_file_api_images__image_id___kind__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lesions/{lesion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lesion */
        get: operations["get_lesion_api_lesions__lesion_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Lesion
         * @description Moves the lesion, its observations and their photographs to the trash together.
         */
        delete: operations["delete_lesion_api_lesions__lesion_id__delete"];
        options?: never;
        head?: never;
        /** Update Lesion */
        patch: operations["update_lesion_api_lesions__lesion_id__patch"];
        trace?: never;
    };
    "/api/lesions/{lesion_id}/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Observations */
        get: operations["list_observations_api_lesions__lesion_id__observations_get"];
        put?: never;
        /** Create Observation */
        post: operations["create_observation_api_lesions__lesion_id__observations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/observations/{observation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Observation */
        get: operations["get_observation_api_observations__observation_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Observation
         * @description Moves the observation and its photographs to the trash together.
         */
        delete: operations["delete_observation_api_observations__observation_id__delete"];
        options?: never;
        head?: never;
        /** Update Observation */
        patch: operations["update_observation_api_observations__observation_id__patch"];
        trace?: never;
    };
    "/api/observations/{observation_id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Observation Images */
        get: operations["list_observation_images_api_observations__observation_id__images_get"];
        put?: never;
        /** Upload Observation Image */
        post: operations["upload_observation_image_api_observations__observation_id__images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Persons */
        get: operations["list_persons_api_persons_get"];
        put?: never;
        /** Create Person */
        post: operations["create_person_api_persons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Person */
        get: operations["get_person_api_persons__person_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Person
         * @description Soft delete (30-day trash); the purge arrives with the data-management features. Needs sudo mode.
         */
        delete: operations["delete_person_api_persons__person_id__delete"];
        options?: never;
        head?: never;
        /** Update Person */
        patch: operations["update_person_api_persons__person_id__patch"];
        trace?: never;
    };
    "/api/persons/{person_id}/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Access */
        get: operations["list_access_api_persons__person_id__access_get"];
        /** Grant Access */
        put: operations["grant_access_api_persons__person_id__access_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{person_id}/access/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Access */
        delete: operations["revoke_access_api_persons__person_id__access__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{person_id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Images */
        get: operations["list_images_api_persons__person_id__images_get"];
        put?: never;
        /**
         * Upload Image
         * @description A photograph of the person not tied to an observation (an overview, for example).
         */
        post: operations["upload_image_api_persons__person_id__images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{person_id}/lesions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Lesions */
        get: operations["list_lesions_api_persons__person_id__lesions_get"];
        put?: never;
        /** Create Lesion */
        post: operations["create_lesion_api_persons__person_id__lesions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable User */
        post: operations["disable_user_api_users__user_id__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable User */
        post: operations["enable_user_api_users__user_id__enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_users__user_id__password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessIn */
        AccessIn: {
            /**
             * Role
             * @enum {string}
             */
            role: "manager" | "viewer";
            /** Username */
            username: string;
        };
        /** AccessOut */
        AccessOut: {
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "manager" | "viewer";
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Username */
            username: string;
        };
        /** BodyMap */
        BodyMap: {
            /** Attribution */
            attribution: string;
            /** Version */
            version: string;
            /** Viewbox */
            viewBox: [
                number,
                number,
                number,
                number
            ];
            /** Views */
            views: {
                [key: string]: components["schemas"]["ViewData"];
            };
            /** Zones */
            zones: components["schemas"]["Zone"][];
        };
        /** Body_upload_image_api_persons__person_id__images_post */
        Body_upload_image_api_persons__person_id__images_post: {
            /** Captured At */
            captured_at?: string | null;
            /** Captured Tz */
            captured_tz?: string | null;
            /** File */
            file: string;
            /**
             * Modality
             * @default camera
             * @enum {string}
             */
            modality: "camera" | "dermatoscope";
            /**
             * Role
             * @default close_up
             * @enum {string}
             */
            role: "overview" | "close_up" | "with_reference" | "other";
        };
        /** Body_upload_observation_image_api_observations__observation_id__images_post */
        Body_upload_observation_image_api_observations__observation_id__images_post: {
            /** Captured At */
            captured_at?: string | null;
            /** Captured Tz */
            captured_tz?: string | null;
            /** File */
            file: string;
            /**
             * Modality
             * @default camera
             * @enum {string}
             */
            modality: "camera" | "dermatoscope";
            /**
             * Role
             * @default close_up
             * @enum {string}
             */
            role: "overview" | "close_up" | "with_reference" | "other";
        };
        /** Credentials */
        Credentials: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Storage
             * @enum {string}
             */
            storage: "ok" | "unavailable";
            /** Version */
            version: string;
        };
        /** ImageOut */
        ImageOut: {
            /** Bytes */
            bytes: number;
            /** Captured At */
            captured_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Height */
            height: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Mime */
            mime: string;
            /** Modality */
            modality: string;
            /** Observation Id */
            observation_id: string | null;
            /** Orientation */
            orientation: number;
            /**
             * Person Id
             * Format: uuid
             */
            person_id: string;
            /** Re Encoded */
            re_encoded: boolean;
            /** Renditions */
            renditions: components["schemas"]["RenditionOut"][];
            /** Role */
            role: string;
            /** Sha256 */
            sha256: string;
            /** Source Format */
            source_format: string;
            /** Width */
            width: number;
        };
        /** InstanceStatus */
        InstanceStatus: {
            /** Claimed */
            claimed: boolean;
            /** Version */
            version: string;
        };
        /** LesionIn */
        LesionIn: {
            /** First Noticed On */
            first_noticed_on?: string | null;
            /**
             * Interval Days
             * @default 90
             */
            interval_days: number;
            /** Label */
            label?: string | null;
            location: components["schemas"]["LocationIn"];
            /** Notes */
            notes?: string | null;
            /**
             * Status
             * @default active
             * @enum {string}
             */
            status: "active" | "removed" | "resolved";
            /** Tags */
            tags?: string[];
            /**
             * Type
             * @default mole
             * @enum {string}
             */
            type: "mole" | "other";
        };
        /** LesionOut */
        LesionOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Due */
            due: boolean;
            /** First Noticed On */
            first_noticed_on: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Interval Days */
            interval_days: number;
            /** Label */
            label: string | null;
            /** Last Observed At */
            last_observed_at: string | null;
            /** Latest Image Id */
            latest_image_id: string | null;
            location: components["schemas"]["LocationOut"];
            /** Next Due On */
            next_due_on: string | null;
            /** Notes */
            notes: string | null;
            /** Observation Count */
            observation_count: number;
            /**
             * Person Id
             * Format: uuid
             */
            person_id: string;
            /** Status */
            status: string;
            /** Tags */
            tags: string[];
            /** Type */
            type: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LesionUpdate */
        LesionUpdate: {
            /** First Noticed On */
            first_noticed_on?: string | null;
            /** Interval Days */
            interval_days?: number | null;
            /** Label */
            label?: string | null;
            location?: components["schemas"]["LocationIn"] | null;
            /** Notes */
            notes?: string | null;
            /** Status */
            status?: ("active" | "removed" | "resolved") | null;
            /** Tags */
            tags?: string[] | null;
            /** Type */
            type?: ("mole" | "other") | null;
        };
        /** LocationIn */
        LocationIn: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Zone */
            zone: string;
        };
        /** LocationOut */
        LocationOut: {
            /** Body Map Version */
            body_map_version: string;
            /** Side */
            side: string;
            /** View */
            view: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Zone */
            zone: string;
        };
        /** ObservationIn */
        ObservationIn: {
            /** Captured At */
            captured_at?: string | null;
            /** Captured Tz */
            captured_tz?: string | null;
            /** Notes */
            notes?: string | null;
            /** Symptoms */
            symptoms?: ("itching" | "bleeding" | "pain" | "looks_different")[];
        };
        /** ObservationOut */
        ObservationOut: {
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /**
             * Captured Local Date
             * Format: date
             */
            captured_local_date: string;
            /** Captured Tz */
            captured_tz: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Images */
            images: components["schemas"]["ImageOut"][];
            /**
             * Lesion Id
             * Format: uuid
             */
            lesion_id: string;
            /** Notes */
            notes: string | null;
            /** Quality Flags */
            quality_flags: string[];
            /** Symptoms */
            symptoms: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ObservationUpdate */
        ObservationUpdate: {
            /** Captured At */
            captured_at?: string | null;
            /** Captured Tz */
            captured_tz?: string | null;
            /** Notes */
            notes?: string | null;
            /** Symptoms */
            symptoms?: ("itching" | "bleeding" | "pain" | "looks_different")[] | null;
        };
        /** PasswordChange */
        PasswordChange: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** PasswordReset */
        PasswordReset: {
            /** New Password */
            new_password: string;
        };
        /** PersonIn */
        PersonIn: {
            /** Birth Year */
            birth_year?: number | null;
            /** Display Name */
            display_name: string;
            /** Skin Tone */
            skin_tone?: string | null;
        };
        /** PersonOut */
        PersonOut: {
            /** Birth Year */
            birth_year: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Experimental Analysis */
            experimental_analysis: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * My Role
             * @enum {string}
             */
            my_role: "owner" | "manager" | "viewer";
            /**
             * Owner User Id
             * Format: uuid
             */
            owner_user_id: string;
            /** Skin Tone */
            skin_tone: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PersonUpdate */
        PersonUpdate: {
            /** Birth Year */
            birth_year?: number | null;
            /** Display Name */
            display_name?: string | null;
            /** Experimental Analysis */
            experimental_analysis?: boolean | null;
            /** Skin Tone */
            skin_tone?: string | null;
        };
        /** RenditionOut */
        RenditionOut: {
            /** Bytes */
            bytes: number;
            /** Height */
            height: number;
            /** Kind */
            kind: string;
            /** Width */
            width: number;
        };
        /** SessionOut */
        SessionOut: {
            /**
             * Instance Claimed
             * @default true
             */
            instance_claimed: boolean;
            /** Sudo Until */
            sudo_until: string | null;
            user: components["schemas"]["UserOut"];
        };
        /** SudoIn */
        SudoIn: {
            /** Password */
            password: string;
        };
        /** UserCreate */
        UserCreate: {
            /** Email */
            email?: string | null;
            /** Password */
            password: string;
            /**
             * Role
             * @default member
             * @enum {string}
             */
            role: "admin" | "member";
            /** Username */
            username: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Disabled At */
            disabled_at: string | null;
            /** Email */
            email: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Language */
            language: string;
            /** Last Login At */
            last_login_at: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "member";
            /** Show Uncertainty */
            show_uncertainty: boolean;
            /** Theme */
            theme: string;
            /** Username */
            username: string;
        };
        /** UserUpdateMe */
        UserUpdateMe: {
            /** Email */
            email?: string | null;
            /** Language */
            language?: ("en" | "es") | null;
            /** Show Uncertainty */
            show_uncertainty?: boolean | null;
            /** Theme */
            theme?: ("system" | "light" | "dark") | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ViewData */
        ViewData: {
            /** Silhouette */
            silhouette: string;
            /** Zones */
            zones: string[];
        };
        /** Zone */
        Zone: {
            /** Anchor */
            anchor: [
                number,
                number
            ];
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ];
            /** Code */
            code: string;
            /** Molemapper Shape */
            molemapper_shape: number;
            /** Name */
            name: string;
            /** Path */
            path: string;
            /**
             * Region
             * @enum {string}
             */
            region: "head" | "trunk" | "arm" | "leg";
            /**
             * Side
             * @enum {string}
             */
            side: "left" | "right" | "midline";
            /**
             * View
             * @enum {string}
             */
            view: "front" | "back";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    claim_api_auth_claim_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    instance_status_api_auth_instance_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceStatus"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_me_api_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateMe"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_auth_me_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_info_api_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    sudo_api_auth_sudo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SudoIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_body_map_api_bodymap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyMap"];
                };
            };
        };
    };
    get_image_api_images__image_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_image_api_images__image_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    image_file_api_images__image_id___kind__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
                kind: "original" | "full" | "preview" | "thumb";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lesion_api_lesions__lesion_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LesionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_lesion_api_lesions__lesion_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_lesion_api_lesions__lesion_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LesionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LesionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_observations_api_lesions__lesion_id__observations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_observation_api_lesions__lesion_id__observations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObservationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_observation_api_observations__observation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                observation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_observation_api_observations__observation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                observation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_observation_api_observations__observation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                observation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObservationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_observation_images_api_observations__observation_id__images_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                observation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_observation_image_api_observations__observation_id__images_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                observation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_observation_image_api_observations__observation_id__images_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_persons_api_persons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"][];
                };
            };
        };
    };
    create_person_api_persons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_person_api_persons__person_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_person_api_persons__person_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_person_api_persons__person_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_access_api_persons__person_id__access_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grant_access_api_persons__person_id__access_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccessIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_access_api_persons__person_id__access__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_images_api_persons__person_id__images_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_image_api_persons__person_id__images_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_api_persons__person_id__images_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_lesions_api_persons__person_id__lesions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LesionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lesion_api_persons__person_id__lesions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LesionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LesionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    create_user_api_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_user_api_users__user_id__disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enable_user_api_users__user_id__enable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_users__user_id__password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordReset"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
