# SPDX-License-Identifier: AGPL-3.0-only
"""The body map: a versioned static asset shared with the frontend.

``zones.json`` is generated by ``tools/bodymap/build.py`` and committed in two
identical copies (here and under ``frontend/src/features/bodymap``); CI checks
they match. Lesions store a zone code plus a point normalised to the view box,
together with the map version, so a later map can be reinterpreted without
touching stored locations.
"""

from __future__ import annotations

import json
from functools import cache
from importlib.resources import files
from typing import Literal

from pydantic import BaseModel

View = Literal["front", "back"]
Side = Literal["left", "right", "midline"]
Region = Literal["head", "trunk", "arm", "leg"]


class Zone(BaseModel):
    code: str
    view: View
    side: Side
    region: Region
    name: str
    molemapper_shape: int
    path: str
    anchor: tuple[float, float]
    bbox: tuple[float, float, float, float]


class ViewData(BaseModel):
    silhouette: str
    zones: list[str]


class BodyMap(BaseModel):
    version: str
    viewBox: tuple[float, float, float, float]  # noqa: N815 - matches the SVG attribute and the JSON file
    attribution: str
    views: dict[View, ViewData]
    zones: list[Zone]

    def zone(self, code: str) -> Zone | None:
        return next((z for z in self.zones if z.code == code), None)


@cache
def body_map() -> BodyMap:
    raw = files("nevus.bodymap").joinpath("zones.json").read_text(encoding="utf-8")
    return BodyMap.model_validate(json.loads(raw))


@cache
def zone_codes() -> frozenset[str]:
    return frozenset(z.code for z in body_map().zones)
