"""session kinds

Revision ID: fdbdf0cc3370
Revises: cfc59ad24620
Create Date: 2026-10-01 22:21:03.193645
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "fdbdf0cc3370"
down_revision: str | None = "cfc59ad24620"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("kind", sa.String(length=16), server_default="local", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.drop_column("kind")

    # ### end Alembic commands ###
