"""appointments

Revision ID: cec8b92c78c1
Revises: e01b2fb43d2c
Create Date: 2026-10-01 21:54:53.921567
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "cec8b92c78c1"
down_revision: str | None = "e01b2fb43d2c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appointments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("report_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_appointments_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["person_id"], ["persons.id"], name=op.f("fk_appointments_person_id_persons"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["report_id"], ["reports.id"], name=op.f("fk_appointments_report_id_reports"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_appointments")),
    )
    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.create_index("ix_appointments_person_id_date", ["person_id", "date"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.drop_index("ix_appointments_person_id_date")

    op.drop_table("appointments")
    # ### end Alembic commands ###
