"""scale references and measurements

Revision ID: 5abbf7f32d3f
Revises: 3bdf92c796a6
Create Date: 2026-10-01 19:50:04.523737
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "5abbf7f32d3f"
down_revision: str | None = "3bdf92c796a6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scale_references",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("image_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("reference_mm", sa.Float(), nullable=True),
        sa.Column("geometry", sa.JSON(), nullable=False),
        sa.Column("mm_per_px", sa.Float(), nullable=False),
        sa.Column("sigma_scale", sa.Float(), nullable=False),
        sa.Column("tilt_deg", sa.Float(), nullable=True),
        sa.Column("analysis_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_id"], ["analyses.id"], name=op.f("fk_scale_references_analysis_id_analyses"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_scale_references_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["image_id"], ["images.id"], name=op.f("fk_scale_references_image_id_images"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scale_references")),
    )
    with op.batch_alter_table("scale_references", schema=None) as batch_op:
        batch_op.create_index("ix_scale_references_image_id", ["image_id"], unique=False)

    op.create_table(
        "measurements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("observation_id", sa.Uuid(), nullable=False),
        sa.Column("lesion_id", sa.Uuid(), nullable=False),
        sa.Column("image_id", sa.Uuid(), nullable=False),
        sa.Column("scale_reference_id", sa.Uuid(), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("shape", sa.JSON(), nullable=False),
        sa.Column("longest_mm", sa.Float(), nullable=False),
        sa.Column("perpendicular_mm", sa.Float(), nullable=False),
        sa.Column("area_mm2", sa.Float(), nullable=False),
        sa.Column("sigma_longest_mm", sa.Float(), nullable=False),
        sa.Column("sigma_perpendicular_mm", sa.Float(), nullable=False),
        sa.Column("sigma_area_mm2", sa.Float(), nullable=False),
        sa.Column("tilt_deg", sa.Float(), nullable=True),
        sa.Column("flags", sa.JSON(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=True),
        sa.Column("confirmed_by", sa.Uuid(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_id"], ["analyses.id"], name=op.f("fk_measurements_analysis_id_analyses"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by"], ["users.id"], name=op.f("fk_measurements_confirmed_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["image_id"], ["images.id"], name=op.f("fk_measurements_image_id_images"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["lesion_id"], ["lesions.id"], name=op.f("fk_measurements_lesion_id_lesions"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observations.id"],
            name=op.f("fk_measurements_observation_id_observations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scale_reference_id"],
            ["scale_references.id"],
            name=op.f("fk_measurements_scale_reference_id_scale_references"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_measurements")),
    )
    with op.batch_alter_table("measurements", schema=None) as batch_op:
        batch_op.create_index("ix_measurements_lesion_id", ["lesion_id"], unique=False)
        batch_op.create_index("ix_measurements_observation_id", ["observation_id"], unique=False)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("card_line_mm", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("card_line_mm")

    with op.batch_alter_table("measurements", schema=None) as batch_op:
        batch_op.drop_index("ix_measurements_observation_id")
        batch_op.drop_index("ix_measurements_lesion_id")

    op.drop_table("measurements")
    with op.batch_alter_table("scale_references", schema=None) as batch_op:
        batch_op.drop_index("ix_scale_references_image_id")

    op.drop_table("scale_references")
    # ### end Alembic commands ###
