"""reminders: snooze, email preference, deliveries

Revision ID: 1cd9374d4ca0
Revises: 5abbf7f32d3f
Create Date: 2026-10-01 20:02:20.660536
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "1cd9374d4ca0"
down_revision: str | None = "5abbf7f32d3f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_deliveries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notification_deliveries_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_deliveries")),
    )
    with op.batch_alter_table("notification_deliveries", schema=None) as batch_op:
        batch_op.create_index("ux_notification_deliveries_once", ["user_id", "channel", "key"], unique=True)

    with op.batch_alter_table("lesions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("snoozed_until", sa.Date(), nullable=True))

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email_reminders", sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("email_reminders")

    with op.batch_alter_table("lesions", schema=None) as batch_op:
        batch_op.drop_column("snoozed_until")

    with op.batch_alter_table("notification_deliveries", schema=None) as batch_op:
        batch_op.drop_index("ux_notification_deliveries_once")

    op.drop_table("notification_deliveries")
    # ### end Alembic commands ###
