"""second factor

Revision ID: 231b5bbc3eea
Revises: 80cd977462ff
Create Date: 2026-10-02 09:00:35.141644
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = "231b5bbc3eea"
down_revision: str | None = "80cd977462ff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_recovery_codes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_recovery_codes_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_recovery_codes")),
    )
    with op.batch_alter_table("user_recovery_codes", schema=None) as batch_op:
        batch_op.create_index("ix_user_recovery_codes_user_id", ["user_id"], unique=False)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("totp_secret", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("totp_enabled_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("totp_last_counter", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("totp_last_counter")
        batch_op.drop_column("totp_enabled_at")
        batch_op.drop_column("totp_secret")

    with op.batch_alter_table("user_recovery_codes", schema=None) as batch_op:
        batch_op.drop_index("ix_user_recovery_codes_user_id")

    op.drop_table("user_recovery_codes")
    # ### end Alembic commands ###
