"""body sessions

Revision ID: 80cd977462ff
Revises: ee2ff1db1b8b
Create Date: 2026-10-01 23:05:25.057548
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "80cd977462ff"
down_revision: str | None = "ee2ff1db1b8b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "body_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("protocol", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("started_by", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["person_id"], ["persons.id"], name=op.f("fk_body_sessions_person_id_persons"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["started_by"], ["users.id"], name=op.f("fk_body_sessions_started_by_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_body_sessions")),
    )
    with op.batch_alter_table("body_sessions", schema=None) as batch_op:
        batch_op.create_index("ix_body_sessions_person_id", ["person_id"], unique=False)

    op.create_table(
        "session_zones",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("zone", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("image_id", sa.Uuid(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["image_id"], ["images.id"], name=op.f("fk_session_zones_image_id_images"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["body_sessions.id"],
            name=op.f("fk_session_zones_session_id_body_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_zones")),
    )
    with op.batch_alter_table("session_zones", schema=None) as batch_op:
        batch_op.create_index("ux_session_zones_session_zone", ["session_id", "zone"], unique=True)

    op.create_table(
        "session_marks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_zone_id", sa.Uuid(), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("lesion_id", sa.Uuid(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("match", sa.String(length=16), nullable=True),
        sa.Column("analysis_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"], ["analyses.id"], name=op.f("fk_session_marks_analysis_id_analyses"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_session_marks_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["lesion_id"], ["lesions.id"], name=op.f("fk_session_marks_lesion_id_lesions"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["session_zone_id"],
            ["session_zones.id"],
            name=op.f("fk_session_marks_session_zone_id_session_zones"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_marks")),
    )
    with op.batch_alter_table("session_marks", schema=None) as batch_op:
        batch_op.create_index("ix_session_marks_lesion_id", ["lesion_id"], unique=False)
        batch_op.create_index("ix_session_marks_zone_id", ["session_zone_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("session_marks", schema=None) as batch_op:
        batch_op.drop_index("ix_session_marks_zone_id")
        batch_op.drop_index("ix_session_marks_lesion_id")

    op.drop_table("session_marks")
    with op.batch_alter_table("session_zones", schema=None) as batch_op:
        batch_op.drop_index("ux_session_zones_session_zone")

    op.drop_table("session_zones")
    with op.batch_alter_table("body_sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_body_sessions_person_id")

    op.drop_table("body_sessions")
    # ### end Alembic commands ###
