"""webhooks and calendar feeds

Revision ID: cfc59ad24620
Revises: cec8b92c78c1
Create Date: 2026-10-01 22:06:34.298176
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "cfc59ad24620"
down_revision: str | None = "cec8b92c78c1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhooks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("preset", sa.String(length=16), nullable=False),
        sa.Column("sealed_url", sa.Text(), nullable=False),
        sa.Column("url_hint", sa.String(length=200), nullable=False),
        sa.Column("sealed_secret", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_status", sa.String(length=16), nullable=True),
        sa.Column("last_error", sa.String(length=200), nullable=True),
        sa.Column("last_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_webhooks_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhooks")),
    )
    with op.batch_alter_table("webhooks", schema=None) as batch_op:
        batch_op.create_index("ix_webhooks_user_id", ["user_id"], unique=False)

    op.create_table(
        "calendar_feeds",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["person_id"], ["persons.id"], name=op.f("fk_calendar_feeds_person_id_persons"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_calendar_feeds_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_feeds")),
    )
    with op.batch_alter_table("calendar_feeds", schema=None) as batch_op:
        batch_op.create_index("ux_calendar_feeds_person_user", ["person_id", "user_id"], unique=True)
        batch_op.create_index("ux_calendar_feeds_token_hash", ["token_hash"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("calendar_feeds", schema=None) as batch_op:
        batch_op.drop_index("ux_calendar_feeds_token_hash")
        batch_op.drop_index("ux_calendar_feeds_person_user")

    op.drop_table("calendar_feeds")
    with op.batch_alter_table("webhooks", schema=None) as batch_op:
        batch_op.drop_index("ix_webhooks_user_id")

    op.drop_table("webhooks")
    # ### end Alembic commands ###
