"""images and renditions

Revision ID: b85ca8527eb6
Revises: 57fafd32a1da
Create Date: 2026-09-23 16:52:18.726916
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "b85ca8527eb6"
down_revision: str | None = "57fafd32a1da"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "images",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("modality", sa.String(length=16), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("bytes", sa.BigInteger(), nullable=False),
        sa.Column("mime", sa.String(length=64), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("orientation", sa.Integer(), nullable=False),
        sa.Column("source_format", sa.String(length=16), nullable=False),
        sa.Column("re_encoded", sa.Boolean(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("captured_tz", sa.String(length=64), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_images_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["person_id"], ["persons.id"], name=op.f("fk_images_person_id_persons"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_images")),
    )
    with op.batch_alter_table("images", schema=None) as batch_op:
        batch_op.create_index("ix_images_person_id", ["person_id"], unique=False)
        batch_op.create_index("ix_images_sha256", ["sha256"], unique=False)

    op.create_table(
        "renditions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("image_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("bytes", sa.BigInteger(), nullable=False),
        sa.Column("mime", sa.String(length=64), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["image_id"], ["images.id"], name=op.f("fk_renditions_image_id_images"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_renditions")),
    )
    with op.batch_alter_table("renditions", schema=None) as batch_op:
        batch_op.create_index("ix_renditions_image_id_kind", ["image_id", "kind"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("renditions", schema=None) as batch_op:
        batch_op.drop_index("ix_renditions_image_id_kind")

    op.drop_table("renditions")
    with op.batch_alter_table("images", schema=None) as batch_op:
        batch_op.drop_index("ix_images_sha256")
        batch_op.drop_index("ix_images_person_id")

    op.drop_table("images")
    # ### end Alembic commands ###
