"""lesions and observations

Revision ID: 4e9653e1edcb
Revises: b85ca8527eb6
Create Date: 2026-09-24 12:28:29.822811
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "4e9653e1edcb"
down_revision: str | None = "b85ca8527eb6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lesions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column("zone_code", sa.String(length=8), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("body_map_version", sa.String(length=32), nullable=False),
        sa.Column("first_noticed_on", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_lesions_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["person_id"], ["persons.id"], name=op.f("fk_lesions_person_id_persons"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lesions")),
    )
    with op.batch_alter_table("lesions", schema=None) as batch_op:
        batch_op.create_index("ix_lesions_person_id", ["person_id"], unique=False)

    op.create_table(
        "observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lesion_id", sa.Uuid(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("captured_tz", sa.String(length=64), nullable=True),
        sa.Column("captured_local_date", sa.Date(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("symptoms", sa.JSON(), nullable=False),
        sa.Column("quality_flags", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_observations_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["lesion_id"], ["lesions.id"], name=op.f("fk_observations_lesion_id_lesions"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observations")),
    )
    with op.batch_alter_table("observations", schema=None) as batch_op:
        batch_op.create_index("ix_observations_captured_at", ["captured_at"], unique=False)
        batch_op.create_index("ix_observations_lesion_id", ["lesion_id"], unique=False)

    with op.batch_alter_table("images", schema=None) as batch_op:
        batch_op.add_column(sa.Column("observation_id", sa.Uuid(), nullable=True))
        batch_op.create_index("ix_images_observation_id", ["observation_id"], unique=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_images_observation_id_observations"),
            "observations",
            ["observation_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("images", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_images_observation_id_observations"), type_="foreignkey")
        batch_op.drop_index("ix_images_observation_id")
        batch_op.drop_column("observation_id")

    with op.batch_alter_table("observations", schema=None) as batch_op:
        batch_op.drop_index("ix_observations_lesion_id")
        batch_op.drop_index("ix_observations_captured_at")

    op.drop_table("observations")
    with op.batch_alter_table("lesions", schema=None) as batch_op:
        batch_op.drop_index("ix_lesions_person_id")

    op.drop_table("lesions")
    # ### end Alembic commands ###
