"""exports

Revision ID: a4729017a735
Revises: 1cd9374d4ca0
Create Date: 2026-10-01 20:17:15.161488
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "a4729017a735"
down_revision: str | None = "1cd9374d4ca0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=True),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("file_name", sa.String(length=200), nullable=True),
        sa.Column("bytes", sa.BigInteger(), nullable=True),
        sa.Column("sealed_passphrase", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["person_id"], ["persons.id"], name=op.f("fk_exports_person_id_persons"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["users.id"], name=op.f("fk_exports_requested_by_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exports")),
    )
    with op.batch_alter_table("exports", schema=None) as batch_op:
        batch_op.create_index("ix_exports_requested_by", ["requested_by"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exports", schema=None) as batch_op:
        batch_op.drop_index("ix_exports_requested_by")

    op.drop_table("exports")
    # ### end Alembic commands ###
